/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_SPDLOG_FFI__
#define __RUST_SPDLOG_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  释放 Rust 分配的字符串
 */
void
free_rs_string (
    char * string);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  使用指定级别记录日志 (使用 u8 作为级别参数)
 */
void
rs_log (
    uint8_t level,
    char const * message);

/** \brief
 *  记录 critical 级别日志
 */
void
rs_log_critical (
    char const * message);

/** \brief
 *  记录 debug 级别日志
 */
void
rs_log_debug (
    char const * message);

/** \brief
 *  记录 error 级别日志
 */
void
rs_log_error (
    char const * message);

/** \brief
 *  记录 info 级别日志
 */
void
rs_log_info (
    char const * message);

/** \brief
 *  记录 trace 级别日志
 */
void
rs_log_trace (
    char const * message);

/** \brief
 *  记录 warn 级别日志
 */
void
rs_log_warn (
    char const * message);

/** \brief
 *  刷新日志缓冲区
 */
void
rs_logger_flush (void);

/** \brief
 *  获取当前日志级别 (返回 u8)
 */
uint8_t
rs_logger_get_level (void);


#include <stdbool.h>

/** \brief
 *  初始化默认日志记录器
 *
 *  # Safety
 *  必须在程序启动时调用一次
 */
bool
rs_logger_init (void);

/** \brief
 *  创建文件日志记录器（简化版，返回是否成功）
 *
 *  # Safety
 *  - path 必须是有效的 UTF-8 字符串
 */
bool
rs_logger_init_file (
    char const * path);

/** \brief
 *  设置日志级别过滤器 (使用 u8 作为参数)
 */
void
rs_logger_set_level (
    uint8_t level);

/** \brief
 *  获取日志库版本信息
 */
char *
rs_logger_version (void);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_SPDLOG_FFI__ */
